language: php
php:
  - "5.3"
  - "5.4"
  - "5.5"
  - "hhvm"
matrix:
  - allow_failures:
    - php: hhvm
  - fast_finish: true
notifications:
  irc: irc.freenode.org#vmdoh
before_script:
  - composer install --prefer-source
script:
  - mkdir -p build/logs
  - phpunit
after_script:
  - php vendor/bin/coveralls -v
